ScopeLift/flexible-voting

.env.example, .gitignore, .gitmodules, README.md, foundry.toml, test/AaveAtokenFork.t.sol, test/FractionalGovernor.sol, test/FractionalPool.t.sol, test/GovToken.sol, test/GovernorCountingFractional.t.sol, test/ProposalReceiverMock.sol
=> Aave test harness

src/ATokenNaive.sol, test/AaveAtokenFork.t.sol, test/FractionalPool.t.sol
RE #7 
Rough usecase:
* there is an ERC20, call it GOV
* GOV is the governance token issued by Protocol
* Protocol inherits from [GovernorCountingFractional](https://github.com/ScopeLift/flexible-voting/blob/master/src/GovernorCountingFractional.sol) and thus will accept fractional voting
* I deposit some GOV into Aave and receive aGOV in return
* aGOV implements [FractionalPool](https://github.com/ScopeLift/flexible-voting/blob/master/src/FractionalPool.sol)-like functionality
* as proposals are made to Protocol, I can express my voting preference on them directly to aGOV
* aGOV will then cast fractionally weighted votes to Protocol according to the expressed voting preferences of its holders
=> Aave naive approach

.gitmodules, foundry.toml, src/ATokenNaive.sol, test/FractionalPool.t.sol
=> Use OZ checkpointing library

src/ATokenFlexVoting.sol, src/FractionalPool.sol, src/interfaces/IFractionalGovernor.sol, src/interfaces/IVotingToken.sol, test/FractionalPool.t.sol
This PR does the following:
* moves Aave overrides so that the initalizer function is near the constructor
* pulls shared interfaces into their own directory to DRY things up
* adds a high-level description of the ATokenFlexVoting contract
=> Atoken miscellaneous cleanup

src/ATokenFlexVoting.sol, test/ATokenFlexVotingFork.t.sol
This PR makes the following small changes to the V3 atoken extension:
* removes two unused libraries
* adds explanation for why we are overriding AToken._transfer
* renames `getPastTotalBalances` (plural) to `getPastTotalBalance` (singular), since there is only one total balance
I noticed these things while I was working on the aave v2 atoken extension.
=> Make minor atoken tweaks

test/ATokenFlexVotingFork.t.sol
We need to make sure that liquidity is taken into consideration when casting votes from aTokens. If some of the governance tokens have been borrowed, this should reduce the amount that the aToken can vote with. We don't want to risk double counting votes!
This was a concern of some folks from Aave, per telegram chat, so I've added some additional test assertions to check for it
=> ATokenFlexVoting: Test that borrowers can vote and that votes aren't double counted

foundry.toml, src/ATokenFlexVoting.sol, src/FractionalPool.sol, src/GovernorCountingFractional.sol, test/ATokenFlexVotingFork.t.sol, test/FractionalGovernor.sol, test/GovToken.sol, test/GovernorCountingFractional.t.sol
This should also make it easier to import this library to implement fractional governors, e.g. [here](https://github.com/gitcoinco/Alpha-Governor-Upgrade/pull/17)
=> Improve OZ remapping to shorten imports

src/GovernorCountingFractional.sol, test/ATokenFlexVotingFork.t.sol, test/FractionalPool.t.sol, test/GovernorCountingFractional.t.sol
=> Make GovernorCountingFractional accept partial votes

src/ATokenFlexVoting.sol, test/ATokenFlexVotingFork.t.sol, test/MockATokenFlexVoting.sol
Compare to the approach in #34. The idea here is that partial votes to `GovernorCountingFractional` will increment the amounts previously cast.
To give a concrete example:
* you have 100 weight to vote with
* the first time you vote, you cast 10 FOR, 20 AGAINST, 0 ABSTAIN
* the governor records 30 votes for you
* the next time you vote, you cast 30 FOR, 5 AGAINST, 10 ABSTAIN
* the governor now records 75 votes for you -- these new votes were added to your previous totals
* finally, you attempt to cast the following votes: 0 FOR, 25 AGAINST, 10 ABSTAIN
* the governor reverts, since if these votes were added to your previous votes you would have voted with a weight of 110, which is more than you have
Here's the gas report run with `forge test --gas-report` (I highlighted the two functions …
=> Support incremental voting on ATokenFlexVoting

src/ATokenFlexVoting.sol, src/FractionalPool.sol, src/GovernorCountingFractional.sol, test/GovernorCountingFractional.t.sol
In GovernorCountingFractional.sol , the ProposalVote struct is defined in the following order: againstVotes , forVotes , abstainVotes . This order aligns with the standard usage in OpenZeppelin's contracts library as well as in Compound's Bravo.
However, the voteData bytes parameter received by the _countVote function requires a different order: forVotes , againstVotes , abstainVotes . While the code currently handles the decoding of this bytes parameter correctly, this inconsistency in the ordering can be problematic for projects that are integrating with the GovernorCountingFractional
contract.
=> M-01 Inconsistent Ordering of Votes

src/GovernorCountingFractional.sol, test/GovernorCountingFractional.t.sol
Fixes https://github.com/ScopeLift/flexible-voting/issues/37
Although docstrings are present above the `_countVoteNominal` and `_countVoteFractional` functions, they do not provide complete information about the purpose of these functions and the parameters passed to them.
=> L-02 Incomplete Docstrings

foundry.toml, package.json, src/ATokenFlexVoting.sol, src/FractionalPool.sol, src/GovernorCountingFractional.sol, test/ATokenFlexVotingFork.t.sol, test/FractionalGovernor.sol, test/GovToken.sol, test/GovernorCountingFractional.t.sol
[OZ recommends]( https://docs.openzeppelin.com/contracts/4.x/) that contracts import its code using the node style so that they have out-of-the box compatibility with [hardhat](https://github.com/NomicFoundation/hardhat).
Note that CI will fail because of a formatting error. I've left the formatting change out of this PR to (a) keep it clean and specific to the issue above and (b) because that formatting error has already been fixed in #40 which will merge before this.
I manually tested that this can now be imported into a hardhat project without issue. Steps to do this were:
1. `mkdir` + `cd` into a new directory
1. `npm init`
3. `npx hardhat`
4. `npm install @openzeppelin/contracts`
5. `npm install ScopeLift/flexible-voting#oz-audit-fixes-N01-hardhat-friendly-imports --save`
6. copy …
=> N-01 OpenZeppelin Imports in Incorrect Format

.github/workflows/ci.yml, .gitmodules, foundry.toml, src/ATokenFlexVoting.sol, src/CometFlexVoting.sol, src/FlexVotingClient.sol, src/interfaces/IFractionalGovernor.sol, src/interfaces/IVotingToken.sol, test/ATokenFlexVotingFork.t.sol, test/CometFlexVotingFork.t.sol
This PR adds a flex voting client contract that is compatible with Compound V3. This was developed through support from a grant from Compound [here](https://questbook.app/dashboard/?grantId=0xeb047900b28a9f90f3c0e65768b23e7542a65163&chainId=10&proposalId=0x21b&isRenderingProposalBody=true)
Currently this PR depends upon [a fork of Compound V3](https://github.com/davidlaprade/comet/) (split from main on May 15, 2023). The [only change](https://github.com/davidlaprade/comet/commit/2921780a8cfe94f2e11cf91ebab1301daf4a76d7) was to make `Comet.updateBasePrincipal` virtual so that we could add checkpointing in the client. My intention is to upstream this change after we're aligned on the architecture of the present PR and it is approved/merged.
This PR also abstracts the flex voting client …
=> Add Compound V3 client contract

src/FlexVotingClient.sol, src/FractionalPool.sol
When importing Flexible Voting into another repository, the forge coverage tool was failing with the error: "Could not read source code for analysis" linked to the imports of interface files from the FlexibleVotingClient contract. While the non-relative imports work fine in the context of this repo, and even in the context of running tests normally when used as an import, they cause an issue for the coverage tool.
It's unclear if this is a bug with foundry or something with our configuration. Regardless, the easiest fix is simply to use relative imports, which we do here.
Read more about the issue here:
https://github.com/foundry-rs/foundry/issues/2915
=> Use relative imports for interfaces

test/FractionalPool.t.sol, test/GovernorCountingFractional.t.sol
This PR bumps OZ to the [latest](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.9.6) pre-5.x.x version. It does not yet include `GovernorCountingFractional` (added in [5.1.0](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v5.1.0))
I'll cut a new 1.2 version of this library once this merges
=> Bump OZ to v4.9.6

.github/workflows/ci.yml, test/FlexVotingClient.t.sol, test/MockFlexVotingClient.sol
Fixes #69
This PR restructures the FlexClient tests to accord with `scopelint spec`. Some tests were renamed. Other tests were added. The resulting spec is:
```
Contract Specification: FlexVotingClient
├── constructor
│   ├──  Sets Governor
│   └──  Self Delegates
├── _rawBalanceOf
│   ├──  Returns Zero For Non Depositors
│   ├──  Increases On Deposit
│   ├──  Decreases On Withdrawal
│   └──  Unaffected By Borrow
├── _castVoteReasonString
│   └──  Returns Descriptive String
├── _selfDelegate
│   └──  Sets Client As The Delegate
├── expressVote
│   ├──  Increments Internal Accouting
│   ├──  Revert When: Depositing After Proposal
│   ├──  Revert When: No Client Weight But Token Weight
│   ├──  Revert On: Double Votes
│   └──  Revert On: Unknown Vote Type
├── castVote
│   ├──  Submits Votes …
```
=> Improve FlexVotingClient test structure

.github/workflows/ci.yml
Remappings were causing the issue that broke CI a few days ago. Figured it out by making a minimal repro [here](https://github.com/davidlaprade/foundry-ci-failure-repro/actions/workflows/ci.yml)
This was caused by a bug in foundry, reported here https://github.com/foundry-rs/foundry/issues/9375 and fixed here https://github.com/foundry-rs/foundry/pull/9379
=> Switch back to nightly build of foundry

.github/workflows/ci.yml, src/FlexVotingClient.sol, test/FlexVotingClient.t.sol
=> Switch to custom errors

src/GovernorCountingFractional.sol
Fixes #52
The `GovernorCountingFractional` contract will be removed in a future release when we bump OZ to v5.1. But for the sake of users that can't upgrade to OZ v5.1, we're marking the use of assembly in that contract as memory-safe.
Per the [solidity docs](https://docs.soliditylang.org/en/latest/assembly.html#memory-safety):
The only assembly we have is here:
```solidity
function _decodePackedVotes(bytes memory voteData)
internal
pure
returns (
uint128 againstVotes,
uint128 forVotes,
uint128 abstainVotes
)
{
assembly {
againstVotes := shr(128, mload(add(voteData, 0x20)))
forVotes := and(_MASK_HALF_WORD_RIGHT, mload(add(voteData, 0x20)))
abstainVotes := shr(128, mload(add(voteData, 0x40)))
}
}
```
This assembly doesn't write to any memory variables. Nor does it allocate any. Instead, …
=> Mark inline assembly as memory-safe

src/FlexVotingClient.sol, src/interfaces/IVotingToken.sol, test/FlexVotingClient.t.sol, test/GovToken.sol, test/MockFlexVotingClient.sol
Fixes https://github.com/ScopeLift/flexible-voting/issues/70
=> Make FlexVotingClient clock agnostic
